import type { ChangeSet, ExecutionSummary, MonitorDetail, MonitorSummary, PublicUser } from "@changelens/contracts";

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();
const minutesFromNow = (minutes: number) => new Date(Date.now() + minutes * 60_000).toISOString();

export const demoUser: PublicUser = {
  id: "10000000-0000-4000-8000-000000000001",
  name: "José Miguel Díaz",
  email: "jmdcore.dev@gmail.com",
  avatarUrl: "/profile/jose-miguel-diaz.png",
  createdAt: "2026-07-01T09:00:00.000Z",
};

export const demoMonitors: MonitorSummary[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    name: "Lumina desk lamp",
    url: "https://jmdcore.github.io/JMD-ChangeLens/demo/lumina-desk-lamp.html",
    hostname: "jmdcore.github.io",
    renderMode: "auto",
    schedule: "hourly",
    isActive: true,
    status: "changed",
    lastRunAt: minutesAgo(8),
    lastChangedAt: minutesAgo(8),
    nextRunAt: minutesFromNow(52),
    successRate: 99.4,
    averageDurationMs: 3120,
    fieldCount: 3,
    createdAt: minutesAgo(12_000),
    updatedAt: minutesAgo(8),
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    name: "Orbit mechanical keyboard",
    url: "https://jmdcore.github.io/JMD-ChangeLens/demo/orbit-keyboard.html",
    hostname: "jmdcore.github.io",
    renderMode: "browser",
    schedule: "every_6h",
    isActive: true,
    status: "healthy",
    lastRunAt: minutesAgo(34),
    lastChangedAt: minutesAgo(722),
    nextRunAt: minutesFromNow(326),
    successRate: 97.8,
    averageDurationMs: 8960,
    fieldCount: 4,
    createdAt: minutesAgo(21_600),
    updatedAt: minutesAgo(34),
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    name: "Atlas API status",
    url: "https://jmdcore.github.io/JMD-ChangeLens/demo/atlas-status.html",
    hostname: "jmdcore.github.io",
    renderMode: "static",
    schedule: "every_15m",
    isActive: true,
    status: "failing",
    lastRunAt: minutesAgo(3),
    lastChangedAt: minutesAgo(1440),
    nextRunAt: minutesFromNow(12),
    successRate: 91.2,
    averageDurationMs: 1290,
    fieldCount: 2,
    createdAt: minutesAgo(43_200),
    updatedAt: minutesAgo(3),
  },
  {
    id: "20000000-0000-4000-8000-000000000004",
    name: "Northstar release notes",
    url: "https://jmdcore.github.io/JMD-ChangeLens/demo/northstar-releases.html",
    hostname: "jmdcore.github.io",
    renderMode: "static",
    schedule: "daily",
    isActive: false,
    status: "paused",
    lastRunAt: minutesAgo(4380),
    lastChangedAt: null,
    nextRunAt: null,
    successRate: 100,
    averageDurationMs: 1840,
    fieldCount: 2,
    createdAt: minutesAgo(10_080),
    updatedAt: minutesAgo(4380),
  },
];

export const demoExecutions: ExecutionSummary[] = [
  {
    id: "30000000-0000-4000-8000-000000000002",
    monitorId: demoMonitors[0]!.id,
    monitorName: demoMonitors[0]!.name,
    trigger: "scheduled",
    status: "succeeded",
    renderer: "cheerio",
    requestedAt: minutesAgo(8),
    startedAt: minutesAgo(8),
    finishedAt: minutesAgo(7.95),
    durationMs: 3120,
    attempt: 1,
    httpStatus: 200,
    finalUrl: demoMonitors[0]!.url,
    output: { title: "Lumina desk lamp", price: 109, availability: "Only 4 left" },
    hasChanges: true,
    changeCount: 2,
    screenshotAvailable: true,
    errorCode: null,
    errorMessage: null,
    blockedReason: null,
    warnings: [],
  },
  {
    id: "30000000-0000-4000-8000-000000000004",
    monitorId: demoMonitors[2]!.id,
    monitorName: demoMonitors[2]!.name,
    trigger: "scheduled",
    status: "failed",
    renderer: null,
    requestedAt: minutesAgo(3),
    startedAt: minutesAgo(3),
    finishedAt: minutesAgo(2.5),
    durationMs: 30_000,
    attempt: 3,
    httpStatus: null,
    finalUrl: null,
    output: null,
    hasChanges: null,
    changeCount: null,
    screenshotAvailable: false,
    errorCode: "NAVIGATION_TIMEOUT",
    errorMessage: "Navigation exceeded the configured 30 second timeout.",
    blockedReason: null,
    warnings: [],
  },
  {
    id: "30000000-0000-4000-8000-000000000003",
    monitorId: demoMonitors[1]!.id,
    monitorName: demoMonitors[1]!.name,
    trigger: "manual",
    status: "succeeded",
    renderer: "playwright",
    requestedAt: minutesAgo(34),
    startedAt: minutesAgo(34),
    finishedAt: minutesAgo(33.85),
    durationMs: 8960,
    attempt: 1,
    httpStatus: 200,
    finalUrl: demoMonitors[1]!.url,
    output: { title: "Orbit 75 mechanical keyboard", price: 184, availability: "Pre-order" },
    hasChanges: false,
    changeCount: 0,
    screenshotAvailable: true,
    errorCode: null,
    errorMessage: null,
    blockedReason: null,
    warnings: [],
  },
  {
    id: "30000000-0000-4000-8000-000000000005",
    monitorId: demoMonitors[0]!.id,
    monitorName: demoMonitors[0]!.name,
    trigger: "scheduled",
    status: "succeeded",
    renderer: "cheerio",
    requestedAt: minutesAgo(68),
    startedAt: minutesAgo(68),
    finishedAt: minutesAgo(67.95),
    durationMs: 2840,
    attempt: 1,
    httpStatus: 200,
    finalUrl: demoMonitors[0]!.url,
    output: { title: "Lumina desk lamp", price: 129, availability: "In stock" },
    hasChanges: false,
    changeCount: 0,
    screenshotAvailable: true,
    errorCode: null,
    errorMessage: null,
    blockedReason: null,
    warnings: [],
  },
];

export const demoChange: ChangeSet = {
  hasChanges: true,
  changeCount: 2,
  added: 0,
  removed: 0,
  changed: 2,
  entries: [
    { field: "availability", kind: "changed", before: "In stock", after: "Only 4 left" },
    { field: "price", kind: "changed", before: 129, after: 109 },
  ],
};

export const demoMonitorDetails: Record<string, MonitorDetail> = Object.fromEntries(
  demoMonitors.map((monitor, monitorIndex) => [
    monitor.id,
    {
      ...monitor,
      webhookUrl: monitorIndex === 0 ? "https://hooks.example.com/changelens" : null,
      retentionDays: 30,
      fields:
        monitorIndex === 0
          ? [
              { key: "title", label: "Product", selector: "h1", valueType: "text", required: true, multiple: false },
              {
                key: "price",
                label: "Price",
                selector: "[data-price]",
                valueType: "currency",
                required: true,
                multiple: false,
              },
              {
                key: "availability",
                label: "Availability",
                selector: "[data-stock]",
                valueType: "text",
                required: false,
                multiple: false,
              },
            ]
          : [
              { key: "title", label: "Title", selector: "h1", valueType: "text", required: true, multiple: false },
              {
                key: "status",
                label: "Status",
                selector: ".state",
                valueType: "text",
                required: false,
                multiple: false,
              },
            ],
    },
  ]),
);

export const demoDashboard = {
  overview: {
    monitorCount: 4,
    healthyCount: 1,
    changedCount: 1,
    failingCount: 1,
    pausedCount: 1,
    runs24h: 146,
    successRate24h: 97.3,
    averageDurationMs24h: 4280,
    changes24h: 7,
  },
  queue: { waiting: 3, active: 2, delayed: 4, failed: 1 },
  recentExecutions: demoExecutions,
};
